dependencies:
- name: mariadb
  version: 4.x.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled,drupal.mariadb.enabled,global.mariadb.enabled
- name: memcached
  version: 2.3.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: memcached.enabled