config:
  target: "https://vilpo-dev.drupal-project-k8s.dev.wdr.io"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up
    - duration: 120
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
scenarios:
  - flow:
      - get:
          url: "/"
