apiVersion: v1
name: drupal
version: 0.3.43
apiVersion: v2
dependencies:
- name: mariadb
  version: 7.5.x
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled,drupal.mariadb.enabled,global.mariadb.enabled
- name: memcached
  version: 4.2.x
  repository: https://charts.bitnami.com/bitnami
  condition: memcached.enabled
- name: mailhog
  version: 3.1.x
  repository: https://codecentric.github.io/helm-charts
  condition: mailhog.enabled
- name: elasticsearch
  version: 7.6.x
  # repository: https://helm.elastic.co
  repository: file://../elasticsearch
  condition: elasticsearch.enabled
- name: silta-release
  version: 0.1.1
  repository: file://../silta-release
