.setup_silta_cli:
  script: |
    echo "Install silta-cli"
    mkdir -p ~/.local/bin
    latest_release_url=$(curl -sL https://api.github.com/repos/wunderio/silta-cli/releases/latest | grep -o -E "https://(.*)silta-(.*)-linux-amd64.tar.gz" | head -1)
    curl -sL $latest_release_url | tar xz -C ~/.local/bin
    silta version

.filter_feature_only:
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: never
    - if: $CI_COMMIT_BRANCH =~ /feature\/test-cluster(\/.*)?/
      when: never
    - if: $CI_COMMIT_BRANCH =~ /feature\/aws-cluster(\/.*)?/
      when: never
    - if: $CI_COMMIT_BRANCH =~ /feature\/aks-cluster(\/.*)?/
      when: never
    - when: on_success

default:
  image: wunderio/silta-cicd:circleci-php8.3-node22-composer2-v1

stages:
  - build

build-job:
  stage: build
  script:
    - !reference [.setup_silta_cli, script]
    - composer install -n --prefer-dist --ignore-platform-reqs --no-dev --optimize-autoloader
    - npm install && npm run build
    # Todo Docker setup
    - silta config set proxy socks5://localhost:1337
  rules:
    - !reference [.filter_feature_only, rules]

