apiVersion: v1
kind: Pod
metadata:
  name: ddos-training-attacker
  namespace: drupal-project-k8s
spec:
  containers:
  # Tool 1: ddosify
  - name: ddosify
    image: ddosify/ddosify
    command: ["/bin/sh"]
    args: 
      - -c
      - |
        ddosify -t https://silta:demo@blackhole.fastly.wdr.io\?cb={{_randomInt}}\&cbx={{_randomInt}} -h 'User-Agent: {{_randomUserAgent}}' \
        -n 3600 -d 3600

  # Tool 2: hey
  - name: hey
    image: ricoli/hey
    command: ["/bin/sh"]
    args:
      - -c
      - |
        hey -z 1h -q 1 -c 1 "https://silta:demo@blackhole.fastly.wdr.io?something=$RANDOM&timestamp=$(date +%s)"

  # Tool 3: curl loop (1 req/sec)
  - name: curl-attacker
    image: curlimages/curl
    command: ["/bin/sh"]
    args:
      - -c
      - |
        while true; do
          curl -s "https://silta:demo@blackhole.fastly.wdr.io?r=$RANDOM" > /dev/null
          sleep 1
        done

  # Tool 4: Legitimate browser traffic
  - name: legitimate-traffic
    image: curlimages/curl
    command: ["/bin/sh"]
    args:
      - -c
      - |
        while true; do
          curl -s -H "User-Agent: Mozilla/5.0 Chrome/120.0" \
          "https://silta:demo@blackhole.fastly.wdr.io" > /dev/null
          sleep 1
        done

  # Tool 5: Vegeta
  - name: vegeta
    image: peterevans/vegeta
    command: ["/bin/sh"]
    args:
      - -c
      - |
        # Generate targets with random values
        while true; do
          echo "GET https://silta:demo@blackhole.fastly.wdr.io?vegeta=$RANDOM&ts=$(date +%s%N)" | \
          vegeta attack -rate=1/s -duration=1s -lazy > /dev/null 2>&1
          sleep 0.1
        done