trigger:
  branches:
    include:
    - feature/devops-build
    # - {{ branch }}

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/feature/devops-build

variables:
  # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#php
  phpVersion: 8.1

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'
