apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cron
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  backOffLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: drupal-cron
            image: "{{ .Values.drupal.image }}"
            command:
            - drush
            - cron
            env:
            {{ include "drupal_env" . | indent 8 }}
          restartPolicy: OnFailure
