apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-drupal
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.php.hashsalt }}
  hashsalt: "{{ .Values.php.hashsalt | b64enc }}"
  {{ else }}
  hashsalt: {{ "{{ randAlphaNum 10 }}" | b64enc }}
  {{- end }}

  {{- if .Values.nginx.basicauth.enabled }}
  .htaccess: | 
    {{ printf "%s:{PLAIN}%s" .Values.nginx.basicauth.credentials.username .Values.nginx.basicauth.credentials.password | b64enc }}
  {{- end }}