apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gdpr-dump
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
data:
  mysql_conf: |
    [mysqldump]
    gdpr-replacements='{{ .Values.gdprDump | toJson }}'
