apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-release"
  labels:
    {{ include "drupal.release_labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  completions: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: post-release
        {{ include "drupal.php-container" . | indent 8 }}
        command: ["/bin/sh", "-c"]
        args:
        - {{ include "drupal.post-release-command" . | quote }}
        volumeMounts:
          {{ include "drupal.volumeMounts" . | indent 8 }}
          - name: reference-data-volume
            mountPath: /var/www/html/reference-data
      {{ include "drupal.imagePullSecrets" . | indent 6 }}
      volumes:
        {{ include "drupal.volumes" . | indent 8 }}
        - name: reference-data-volume
          persistentVolumeClaim:
            claimName: {{ include "drupal.referenceEnvironment" . }}-reference-data
