{{- if .Values.referenceData.enabled }}
{{- if eq .Values.referenceData.referenceEnvironment .Values.environmentName }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-refdata
  labels:
    {{ include "drupal.release_labels" . | indent 4 }}
spec:
  schedule: {{ .Values.referenceData.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reference-data-cron
            {{ include "drupal.php-container" . | indent 12 }}
            command: ["/bin/sh", "-c"]
            args:
              - {{ .Values.referenceData.command | quote }}
            resources:
{{ .Values.php.resources | toYaml | indent 14 }}
          restartPolicy: OnFailure
          volumes:
            {{ include "drupal.volumes" . | indent 12 }}

          {{ include "drupal.imagePullSecrets" . | indent 10 }}
{{- end }}
{{- end }}
---