{{- if .Values.shell.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "drupal.environment.hostname" . }}-shell
  labels:
    {{ include "shell.release_labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
    - name: ssh
      port: 22
  selector:
    {{ include "shell.release_labels" . | indent 4 }}
{{- end }}
---