{{- if .Values.shell.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-shell
  labels:
    {{ include "drupal.release_labels" . | indent 4 }}
    service: shell
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "drupal.release_labels" . | indent 6 }}
      service: shell
  template:
    metadata:
      labels:
        {{ include "drupal.release_labels" . | indent 8 }}
        service: shell
    spec:
      containers:
      - name: shell
        {{ include "shell.ssh-container" . | indent 8 }}
        resources:
{{ .Values.php.resources | toYaml | indent 10 }}
      volumes:
        {{ include "shell.volumes" . | indent 8}}
      {{ include "drupal.imagePullSecrets" . | indent 6 }}
{{- end }}
---