apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.branchNameUrl }}-shell
  labels:
    {{ include "drupal.release_labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
    - name: ssh
      port: 22
  selector:
    app: {{ .Values.app | quote }}
    release: {{ .Release.Name }}
