parameters:
  monolog.channel_handlers:
    default:
      handlers:
        - name: 'stream'
          formatter: 'normalizer'
#          processors:
#            - 'message_placeholder'
#            - 'current_user'
#            - 'request_uri'
#            - 'ip'
#            - 'referer'
#            - 'filter_backtrace'

services:
  monolog.handler.stream:
    class: Monolog\Handler\StreamHandler
    # The minimum logging level DEBUG = 100
    arguments: ['php://stderr', 100]
