parameters:
  monolog.channel_handlers:
     # Log to stderr by default.
     default: ['stream']

services:
  monolog.handler.stream:
    class: Monolog\Handler\StreamHandler
    # The minimum logging level DEBUG = 100
    arguments: ['php://stderr', 100]
