parameters:
  monolog.channel_handlers:
    # Log to the stdout by default.
    default:
      handlers:
        - name: 'stream'
          formatter: 'drush'
  monolog.processors:
    - 'message_placeholder'
    - 'current_user'
    - 'request_uri'
    - 'ip'
    - 'referer'
    - 'filter_backtrace'

services:
  monolog.handler.stream:
    class: Monolog\Handler\StreamHandler
    arguments: ['php://stdout', 200]
