{{- if .Values.backup.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-backup
  labels:
    name: {{ .Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-backup
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.backup.storage }}
  storageClassName: {{ .Values.backup.storageClassName }}
  {{- if .Values.backup.csiDriverName }}
  csi:
    driver: {{ .Values.backup.csiDriverName }}
    volumeHandle: {{ .Release.Namespace }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-backup
    volumeAttributes:
      remotePathSuffix: /{{ .Release.Namespace }}/backup
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-backup
  labels:
    app: {{ .Values.app | quote }}
    release: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.backup.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.backup.storage }}
{{- if eq .Values.backup.storageClassName "silta-shared" }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-backup
{{- end }}
{{- end }}