apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-drupal
  annotations:
    {{- if (index .Values "silta-release").downscaler.enabled }}
    auto-downscale/down: "false"
    {{- end }}
    {{- if and (eq .Values.cluster.type "gke") (.Values.backendConfig) }}
    cloud.google.com/backend-config: '{"default":"{{ .Release.Name }}-drupal"}'
    {{- end }}
    {{- if .Values.cluster }}
    {{- if .Values.cluster.vpcNative }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
    {{- end }}
    {{- if .Values.nginx.sessionAffinity }}
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky-drupal"
    {{- end }}
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  type: ClusterIP
  # We explicitly unset this, in case the application is currently downscaled.
  externalName: null
  ports:
    - name: web
      port: 80
      targetPort: 8080
  selector:
    {{- include "drupal.release_selector_labels" . | nindent 4 }}
    deployment: drupal
