{{- range $index, $mount := .Values.mounts }}
#Trimmed release name to fit *it*, sha256sum(7 chars), $index and '-' separators together into a single 63 character string
{{- $releaseNameTrimmed := substr 0 (int (sub 54 (len $index))) $.Release.Name }}
{{- if eq $mount.enabled true }}
{{- if and (not (hasKey $mount "configMapName")) (not (hasKey $mount "secretName")) -}}
{{- if and (eq $mount.storageClassName "silta-shared") ( eq ($.Values.cluster.siltaSharedStorageVersion | int)  1) }}
# Mount-enabled: {{ $mount.enabled  }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-{{ $index }}
  labels:
    name: {{ $releaseNameTrimmed }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-{{ $index }}
    {{- include "drupal.release_labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ $mount.storage }}
  storageClassName: {{ $mount.storageClassName }}
  {{- if $mount.csiDriverName }}
  csi:
    driver: {{ $mount.csiDriverName }}
    volumeHandle: {{ $.Release.Name }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-{{ $index }}
    volumeAttributes:
      remotePathSuffix: /{{ $.Release.Namespace }}/{{ $.Values.environmentName }}/{{ $index }}
  {{- end }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if and (eq $mount.storageClassName "silta-shared") ( eq ($.Values.cluster.siltaSharedStorageVersion | int) 2) }}
  name: {{ $.Release.Name }}-v2-{{ $index }}
  {{- else }} 
  name: {{ $.Release.Name }}-{{ $index }}
  {{- end }}
  labels:
    {{- include "drupal.release_labels" $ | nindent 4 }}
  annotations:
    storage.silta/storage-path: {{ $.Values.environmentName | default $.Release.Name }}/{{ $index }}
spec:
  {{- if and (eq $mount.storageClassName "silta-shared") ( eq ($.Values.cluster.siltaSharedStorageVersion | int) 2) }}
  storageClassName: silta-shared-nfs
  {{- else }}
  storageClassName: {{ $mount.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $mount.storage }}
{{- if and (eq $mount.storageClassName "silta-shared") ( eq ($.Values.cluster.siltaSharedStorageVersion | int) 1) }}
  selector:
    matchLabels:
      name: {{ $releaseNameTrimmed }}-{{ $.Release.Namespace | sha256sum | trunc 7 }}-{{ $index }}
{{- end }}
---
{{- end -}}
{{- end }}
{{- end }}

{{- if .Values.referenceData.enabled }}
{{- if eq .Values.referenceData.referenceEnvironment .Values.environmentName }}
{{- if and (eq .Values.referenceData.storageClassName "silta-shared") ( eq ($.Values.cluster.siltaSharedStorageVersion | int) 1) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace | sha256sum | trunc 7 }}-reference-data
  labels:
    name: {{ .Release.Name }}-{{ .Release.Namespace | sha256sum | trunc 7 }}-reference-data
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.referenceData.storage }}
  storageClassName: {{ .Values.referenceData.storageClassName }}
  {{- if .Values.referenceData.csiDriverName }}
  csi:
    driver: {{ .Values.referenceData.csiDriverName }}
    volumeHandle: {{ .Release.Name }}-{{ .Release.Namespace | sha256sum | trunc 7 }}-reference-data
    volumeAttributes:
      remotePathSuffix: /{{ .Release.Namespace }}/{{ .Values.environmentName }}/reference-data
  {{- end }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if and (eq .Values.referenceData.storageClassName "silta-shared") ( eq ($.Values.cluster.siltaSharedStorageVersion | int)  2) }}
  name: {{ include "drupal.referenceEnvironment" . }}-v2-reference-data
  {{- else }}
  name: {{ include "drupal.referenceEnvironment" . }}-reference-data
  {{- end }}
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
  annotations:
    storage.silta/storage-path: {{ .Values.environmentName | default .Release.Name }}/reference-data
spec:
  {{- if and (eq .Values.referenceData.storageClassName "silta-shared") ( eq ($.Values.cluster.siltaSharedStorageVersion | int) 2) }}
  storageClassName: silta-shared-nfs
  {{- else }}
  storageClassName: {{ .Values.referenceData.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.referenceData.storage }}
{{- if and (eq .Values.referenceData.storageClassName "silta-shared") ( eq ($.Values.cluster.siltaSharedStorageVersion | int) 1) }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-{{ .Release.Namespace | sha256sum | trunc 7 }}-reference-data
{{- end }}
{{- end }}
{{- end }}
---
