{{- $mariadbha := index .Values "mariadb-ha" }}
{{- if $mariadbha.enabled }}
{{- if not ( .Capabilities.APIVersions.Has "mariadb.mmontes.io/v1alpha1" ) }}
{{- fail "API mariadb.mmontes.io/v1alpha1 unavailable, ask cluster administrator to enable mariadb-operator support in Silta cluster first!" }}
{{- end }}
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: {{ .Release.Name }}-mariadb-ha
spec:
  image: {{ $mariadbha.image | quote }}
  imagePullPolicy: {{ $mariadbha.imagePullPolicy | quote }}
  port: 3306
  replicas: {{ $mariadbha.replicas }}
  # TODO: test 1 replica, check data migration to 3 and then back to 1
  {{- if gt (int $mariadbha.replicas) 1 }}
  galera:
    enabled: true
  {{- end }}
  rootPasswordSecretKeyRef:
    name: {{ .Release.Name }}-mariadb-ha
    key: password

  # TODO: expose this?  
  # replication:
  #   enabled: true
  #   primary:
  #     podIndex: 0
  #     automaticFailover: true
  #   replica:
  #     waitPoint: AfterSync
  #     gtid: CurrentPos
  #     replPasswordSecretKeyRef:
  #       name: mariadb
  #       key: password
  #     connectionTimeout: 10s
  #     connectionRetries: 10
  #     syncTimeout: 10s
  #   syncBinlog: true
  
  volumeClaimTemplate:
    resources:
      requests:
        storage: {{ $mariadbha.persistence.size | quote}}
    accessModes:
      - ReadWriteOnce

  {{- if $mariadbha.resources }}
  resources:
    {{ $mariadbha.resources | toYaml | nindent 4 }}
  {{- end }}

  # Error writing Galera config: open /etc/mysql/mariadb.conf.d/0-galera.cnf: permission denied
  # https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md#permission-denied-writing-galera-configuration
  podSecurityContext:
    runAsUser: 0

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-ha
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
type: Opaque
data:
  password: "{{ $mariadbha.password | b64enc }}"
  
{{- end }}
