# Allow access to drupal or varnish pods from the ingress in the silta-cluster namespace
{{- $id := "allow-ingress" -}}
{{- $podSelectors := ternary (dict "service" "varnish") (dict "app" "drupal") .Values.varnish.enabled -}}
{{- $from := list (dict "namespaceSelector" (dict "matchLabels" (dict "name" "silta-cluster"))) -}}
{{- $params := mergeOverwrite . (dict "id" $id "additionalPodSelectors" $podSelectors "from" $from) -}}
{{ include "silta-release.networkPolicy" $params }}
