apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-release
  labels:
    release: {{ .Release.Name }}
    release.silta/config: release-configmap
data:
  releaseName: {{ .Release.Name | quote }}
  branchName: {{ .Values.branchName | quote }}
  chartName: {{ .Chart.Name | quote }}
  chartVersion: {{ .Chart.Version | quote }}
