apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-shell
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.shell.gitAuth.apiToken }}
  gitAuth.apiToken: "{{ .Values.shell.gitAuth.apiToken | b64enc }}"
  {{- end }}