{{- if .Values.solr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-solr
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8983
  selector:
    {{- include "drupal.release_selector_labels" . | nindent 4 }}
    statefulset: solr
{{- end }}
