{{- if .Values.varnish.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-varnish
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.varnish.secret }}
  control_key: {{ printf "%s\n" .Values.varnish.secret | b64enc }}
  {{ else }}
  control_key: {{ "not-a-secret-123\n" | b64enc }}
  {{ end }}
{{- end }}